name: CI

on:
  pull_request: {}
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: rustup toolchain install stable --profile minimal
    - run: cargo +stable build

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: rustup toolchain install stable --profile minimal
    - run: cargo +stable test --all-features
